import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Providers from "@/hooks/providers";
import ToasterContext from "@/context/ToasterContext";
import dynamic from "next/dynamic";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quizzify",
  description: "Generated by create next app",
};
const Navbar = dynamic(() => import("../components/Navbar"), { ssr: false });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <Providers>
          <ToasterContext />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
