import DesktopSidebar from "@/components/admins/desktopSidebar/DesktopSidebar";
import MobileFooter from "@/components/admins/mobileFooter/MobileFooter";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "MindMingle",
  description: "Generated by create next app",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      {/* <Navbar /> */}
      <div className="max-w-[1100px] mx-auto">
        <DesktopSidebar />
        <MobileFooter />
        <div className="lg:ml-[200px] p-5">{children}</div>
      </div>
    </div>
  );
};

export default layout;
